### ISSUE TITLE
关于CSV的问题

### ISSUE THREAD

**Issue by coderSun20201112** [secretflow/easy-psi#6]
老师，我是通过Easy-PSI-0.2.0beta.tar.gz方式快速部署的，然后在使用过程中，请教几个问题：

问题1：是否支持直接从数据库来读取求交数据，不再从CSV读取？

问题2：Alice节点每次发起任务，都需要Bob节点审核，能否通过配置改成默认审核通过，绕开Bob节点审核？

问题3：PSI结果存放到CSV中，但没有选择哪些列可以写入CSV中，目前可以自定义哪些列写入结果CSV吗？

**Comment by coderSun20201112** [comment]
问题4：在执行成功的情况下是否可以再次执行:
问题5：是否可以定时发起？

**Comment by wenkesong-li** [comment]
1，3，4，5不支持
问题2 ： 0.3.0 alice添加bob时 配置信任bob bob发起任务时审批会自动跳过 如果想绕过bob节点的审核 需要bob信任alice节

**Comment by coderSun20201112** [comment]
> 1，3，4，5不支持 问题2 ： 0.3.0 alice添加bob时 配置信任bob bob发起任务时审批会自动跳过 如果想绕过bob节点的审核 需要bob信任alice节

好的，我今天再试试v0.3.0beta版本，谢谢老师
